sudo: false

matrix:
    include:
        - env:
            CABALVER=1.22
            GHCVER=7.10.3

          addons: {
              apt: {
                  packages: [
                      ghc-7.10.3,
                      alex-3.1.4,
                      happy-1.19.5,
                      cabal-install-1.22,
                      zlib1g-dev
                  ],
                  sources: [hvr-ghc]
              }
          }

before_install:

    - PATH="$HOME/.cabal/bin:$PATH"
    - PATH="/opt/ghc/$GHCVER/bin:$PATH"
    - PATH="/opt/cabal/$CABALVER/bin:$PATH"
    - export PATH

    - env
    - ghc --version
    - cabal --version
    - alex --version
    - happy --version
    - cabal update

install:

    - travis_retry git clone git://git.haskell.org/ghc --recurse-submodules

    # Travis clones the project into ".", but we need it as a child directory
    # of "ghc/". For this reason, we - rather hackily - move the GHC-Shake
    # ".git"  directory into the appropriate location, and perform a hard reset
    # in order to regenerate the GHC-Shake files.
    - mkdir ghc/shake-build
    - mv .git ghc/shake-build
    - ( cd ghc/shake-build && git reset --hard HEAD )

    - ( cd ghc/shake-build && cabal install --only-dependencies )

    - ( cd ghc && ./boot )
    - ( cd ghc && ./configure )

script:
    - ./ghc/shake-build/build.sh -j --no-progress

cache:
    directories:
        - $HOME/.cabal

notifications:
    irc:
        on_success: always # always/never/change
        on_failure: always
        channels:
            - "chat.freenode.net#shaking-up-ghc"
        template:
            - "#%{build_number} finished in %{duration}. %{message}"
            - "Repo: %{repository_slug}, branch: %{branch}"
            - "%{author}: %{commit_subject}"
            - "Build details: %{build_url}"
